#!/bin/sh

. asutils-init

asutils_init_init "" "exec bash"

echo "${0##*/}: warning: this script modifies system"

asutils_init_kernfs
asutils_init_env

# Используем то, что /etc/mtab - это симлинк на /proc/mounts
echo "${0##*/}: mounting all file systems read-only"
mount -o ro -a || : # \"mount -a\" may return non-zero without reason

asutils_init_tty

if grep -q "^[^ ]* /tmp" /proc/mounts; then
	mount -o remount,rw /tmp
else
	mount -t tmpfs none /tmp
fi

/etc/init.d/udev start

exec bash
